version: "3.8"

services:
  soukyoku-log:
    build: ./php
    depends_on:
      - mysql
    working_dir: /var/www/html
    ports:
      - 443:443
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ..:/var/www/html:delegated
      - ~/.ssh:/root/.ssh:delegated,ro

  nginx:
    image: nginx:1.20.1-alpine
    depends_on:
      - soukyoku-log
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: '"*"'
      FASTCGI_PASS: soukyoku-log:9000
      FASTCGI_READ_TIMEOUT: 300
      ROOT_PATH: /var/www/html/public
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/templates/default.conf.template:delegated
      - ..:/var/www/html:delegated,ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: local_soukyoku
      MYSQL_USER: local
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql

  test_mysql:
    image: mysql:5.7
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: test_soukyoku
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
