version: "3.8"

services:
  laravel-app:
    build: ./php
    depends_on:
      - mysql
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ..:/var/www/html:delegated
      - ~/.ssh:/root/.ssh:delegated,ro
    working_dir: /var/www/html
    networks:
      - front-tier
      - back-tier

  nginx:
    image: nginx:1.20.1-alpine
    depends_on:
      - laravel-app
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: '"*"'
      FASTCGI_PASS: laravel-app:9000
      FASTCGI_READ_TIMEOUT: 300
      ROOT_PATH: /var/www/html/public
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/templates/default.conf.template:delegated
      - ..:/var/www/html:delegated,ro
    networks:
      - front-tier

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_local
      MYSQL_USER: local
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
    networks:
      - back-tier

  test_mysql:
    image: mysql:8.0
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    networks:
      - back-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - back-tier

  redis:
    image: redis:alpine3.12
    volumes:
      - ./redis:/data
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
